### PR TITLE
update to build all platforms

### PR DESCRIPTION
**Pull request by SimonDanisch**
And use the version in build_tarballs

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Yizzz :) Can we make a tag with this?

**Comment by SimonDanisch** [comment]
*bump*

**Comment by SimonDanisch** [comment]
We also might want to move this to JuliaGraphics?

**Comment by Gnimuc** [comment]
@SimonDanisch sorry, I missed the email notification yesterday. new release tagged.

**Comment by SimonDanisch** [comment]
thanks a lot :)

**Comment by Gnimuc** [comment]
I agree to move this repo to JuliaGraphics, but it looks like I don't have the permission to transfer it to JuliaGraphics.

**Comment by Gnimuc** [comment]
@SimonDanisch OK, I just deleted the forked repo and then transferred successfully :)

**Pull request merged**
